# Generated by Django 4.1.5 on 2023-01-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_post_categoria_profile_categoria"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categoria",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="categoria",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="categoria",
            new_name="category",
        ),
    ]
